language: java

sudo: false

jdk: oraclejdk8

before_install: mvn package

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $GITHUB_TOKEN
  file: target/demo.jar
  on:
    tags: true
