# Action name
name: Super Action

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    super-job:
        runs-on: alpine
        container:
            image: openjdk:8-jdk-alpine
        steps:
            - name: super-step
              shell: bash
              run: |
                # Whatever commands you want to run here using the container with your
                # new Docker image at ghcr.io!>
                echo "--This is running in my custom Docker image--"
